name: lab_master_screen
description: lab master screen
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

##-- UI --##
  quds_ui_kit: ^0.0.7+10              # widget collection
  flame: ^1.10.0
  syncfusion_flutter_core: ^23.1.43

  flutter_native_splash: ^2.3.5

  easy_date_timeline: ^1.0.2

  home_widget: ^0.3.0 # create little app

  flutter_gen: ^5.3.2                 # generate pubspec

  flutter_svg: ^2.0.9                 # svg
  svg_path_parser: ^1.1.1             # ?? svg path parser
  animated_svg: ^2.0.0                # ?? animated svg
  path_drawing: ^1.0.1                # path drawing

  fl_chart: ^0.64.0                   # chart
  syncfusion_flutter_charts: ^23.1.43 # chart
  sleek_circular_slider: ^2.0.1

  file_picker: ^6.0.0                 # file picker
  better_open_file: ^3.6.4            # ?? file picker (without permissions)

  awesome_notifications: ^0.8.2       # notifications
  flutter_local_notifications: ^16.1.0

  qr_code_scanner: ^1.0.1             # qr code scanner
  mobile_scanner: ^3.5.2

  draggable_home: ^1.0.5              # draggable screen (show/hide header/body)

  animations: ^2.0.8                  # animation controller
  flutter_animate: ^4.2.0+1           # animation controller
  spring: ^2.0.2                      # ?? animation controller
  animate_do: ^3.1.2                  # ?? animation controller

  lottie: ^2.7.0                      # lottie animations
  touchable: ^1.0.2                   # ?? touchable widget (gestures and animations)
  animated_toggle_switch: ^0.8.0      # ?? animated toggle
  confetti: ^0.7.0                    # ?? animate stars
  like_button: ^2.0.5                 # ?? like button
  progress_state_button: ^1.0.4
  pretty_animated_buttons: ^0.0.1
  swipeable_button_view: ^0.0.2       # ?? button swipe loading and open page
  fsearch_nullsafety: ^2.0.0          # ?? search box (camera/mic/..)
  flutter_tilt: ^2.0.10
  parallax_sensors_bg: ^1.0.1
  parallax_image_ns: ^0.3.2
  carousel_images: ^1.1.2
  sensors_plus: ^3.1.0

  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0                     # shimmer

  badges: ^3.1.2

  material_dialogs: ^1.1.4

  showcaseview: ^2.0.3

  indexed_list_view: ^2.0.2           # ?? indexed listview
  flutter_scroll_to_top: ^2.3.0       # ?? scroll to top list
  select_dialog: ^2.0.1               # ?? select list dialog
  group_button: ^5.3.3                # ?? select list/grid dialog
  flutter_filter_dialog: ^1.2.0       # ?? filter dialog
  list_treeview: ^0.3.1
  flutter_fancy_tree_view: ^1.4.1
  positioned_scroll_observer: ^2.2.2
  scroll_to_index: ^3.0.1
  sps_drop_down_list: ^1.2.2
  intl_phone_field: ^3.2.0
  sticky_and_expandable_list: ^1.1.3

  fluttertoast: ^8.2.2
  flutter_smart_dialog: ^4.9.5

  syncfusion_flutter_gauges: ^23.1.43 # ?? gauge stepper
  easy_stepper: ^0.8.1                # ?? stepper
  im_stepper: ^1.0.1+1                # ?? stepper

  spflutter_number_picker: ^1.5.0     # ?? number_picker

  circular_countdown_timer: ^0.2.3    # ?? countdown timer

  intro_views_flutter: ^3.2.0         # ?? intro views (first app lunch)

  expandable: ^5.0.1                  # ?? expandable widget

  full_screen_image: ^2.0.0
  extended_image: ^8.1.1

  horizontal_card_pager: ^1.1.1       # ?? horizontal widget <= Set Custom
  card_swiper: ^3.0.1                 # ?? horizontal widget <= Set Custom
  horizontal_list: ^0.0.7             # ?? horizontal widget <= Set Custom
  carousel_slider: ^4.2.1

  flutter_keyboard_visibility: ^5.4.1 # ?? keyboard visibility changes

  dash_chat_2: ^0.0.19                # ?? chat screen

  flutter_improved_scrolling: ^0.0.3  # ?? scrolling (Web/Desktop)

  beamer: ^1.5.6                      # ?? navigation screens (Desktop/Web) [Get?]
  routemaster: ^1.0.1

  top_snackbar_flutter: ^3.1.0        # ?? top snack bar

  image_picker: ^1.0.4                # ?? image picker
  image_watermark: ^0.0.5
  camerawesome: ^1.4.0

  audioplayers: ^5.2.0                # ?? audio players

  dropdown_button2: ^2.3.9            # ?? combo box (select item)
  circular_menu: ^2.0.1               # ?? circular menu
  star_menu: ^3.1.4                   # ?? star menu (fab button & popup menu)
  custom_pop_up_menu: ^1.2.4
  flutter_expandable_fab: ^2.0.0

  slide_popup_dialog_null_safety: ^1.0.0

  convex_bottom_bar: ^3.2.0           # ?? bottom bar Navigation screens
  animated_notch_bottom_bar: ^1.0.0   # ?? bottom bar Navigation screens
  google_nav_bar: ^5.0.6              # ?? bottom bar Navigation screens
  curved_drawer_fork: ^0.0.1+1        # ?? vertical tab bar
  scroll_navigation: ^1.3.2           # ?? scroll navigation
  custom_navigation_bar: ^0.8.2
  bottom_navy_bar: ^6.0.0

  typewritertext: ^2.3.0
  animated_text_kit: ^4.2.2
  toggle_switch: ^2.1.0

  font_awesome_flutter: ^10.6.0

  smooth_page_indicator: ^1.1.0       # ?? page indicator (dot in button image/screen)
  dots_indicator: ^3.0.0

  flutter_floating_bottom_bar: ^1.2.0 # ?? floating bottom bar (hide/show on scroll list)
  floating_bottom_bar: ^0.0.2         # ?? floating bottom bar (hide/show on scroll list)

  autocomplete_textfield: ^2.0.1      # ?? autocomplete text field
  flutter_typeahead: ^4.8.0

  persian_linear_date_picker: ^0.0.2  # ?? persian date picker
  sps_persian_datetime_picker: ^2.0.0 # ?? persian date picker
  table_calendar_jalali: ^1.0.1

  flutter_screen_scaler: ^2.1.0       # ?? responsive
  responsive_sizer: ^3.2.0            # ?? responsive
  window_manager: ^0.3.7

  google_fonts: ^6.1.0
  fluentui_system_icons: ^1.1.220

  auto_size_text: ^3.0.0

  cached_network_image: ^3.3.0

  drag_and_drop_lists: ^0.3.3
  flutter_reorderable_list: ^1.3.1
  animated_list_plus: ^0.5.2

  flutter_slider_drawer: ^2.1.3

  scroll_app_bar_2_0_0_custom_fix: ^2.0.3
  flutter_focus_watcher: ^2.0.0
  before_after_image_slider_nullsafty: ^1.0.1
  reviews_slider: ^2.0.0
  filling_slider: ^0.0.3
  status_bar_control: ^3.2.1


##-- SETTING --##
  package_info_plus: ^4.2.0           # package info
  wakelock: ^0.6.2                    # wakelock


##-- UTILITY --##
  get: ^4.6.6                         # state management
  flutter_bloc: ^8.1.3                # ?? state management
  bloc: ^8.1.2                        # ?? state management
  flutter_riverpod: ^2.4.5
  riverpod: ^2.4.5
  mobx: ^2.2.1

  win32: ^5.0.9

  http: ^1.1.0                        # http management
  chopper: ^7.0.9                     # http client generator
  dio: ^5.3.3
  intl: ^0.18.1

  flutter_blue: ^0.8.0                # ?? bluetooth management

  formz: ^0.6.1                       # ?? validation

  permission_handler: ^11.0.1         # permission
  path_provider: ^2.1.1
  path: ^1.8.3

  easy_localization: ^3.0.3


  flutter_cache_manager: ^3.3.1
  image_gallery_saver: ^2.0.3
  background_downloader: ^7.12.2
  uuid: ^4.1.0

  network_info_plus: ^4.1.0

  timezone: ^0.9.2

  device_info_plus: ^9.1.0

  internet_connection_checker: ^1.0.0+1

  vpn_connection_detector: ^1.0.5

  icons_launcher: ^2.1.4

  url_launcher: ^6.2.1

  in_app_review: ^2.0.8

  flutter_secure_storage: ^9.0.0      # save little values
  shared_preferences: ^2.2.2          # save little values
  printing: ^5.11.0                   # printing
  vibration: ^1.8.3                   # vibration controller
  share_plus: ^7.2.1                  # share content
  speech_to_text: ^6.4.0

  xml: ^6.4.2                         # ?? xml parser
  persian_number_utility: ^1.1.3      # ?? persian utility
  archive: ^3.4.6                     # ?? encode/decode zip
  connectivity_plus: ^5.0.1           # ?? net connect status
  location: ^5.0.3                    # ?? location Android/iOS
  flutter_downloader: ^1.11.4         # ?? downloader
  flutter_app_name: ^0.1.1            # ?? change app name command (customized is sp_flutter_rename_app)
  platform_info: ^4.0.2               # ?? BuildMode / HostPlatform / OperatingSystem
  open_file: ^3.3.2                   # ?? open files with string
  time_machine: ^0.9.17               # ?? time manager
  flutter_native_timezone_updated_gradle: ^2.0.3

  objectbox: ^2.3.1                   # ?? DB
  realm: ^1.5.0                       # ?? DB
  hive: ^2.2.3                        # ?? DB
  isar: ^3.1.0+1                      # ?? DB
  freezed: ^2.4.5                     # ?? DB
  flutter_orm: ^0.0.8                 # ?? DB

  equatable: ^2.0.5                   # compare two class
  collection: ^1.18.0                 # ?? compare two class



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
